### ISSUE TITLE
[REQUEST] Web integration EMAIL option

### ISSUE THREAD

**Issue by AmazedMender16** [Xephi/AuthMeReloaded#1019]
Add a option to add email
to web integration please :(\

And case sensitive PLEASE

**Comment by ljacqu** [comment]
Are you referring to add an email field in https://github.com/AuthMe/AuthMeReloaded/tree/master/samples/website_integration ? And it would just save the email to the database?
I don't think someone from the AuthMe team has the capacity to implement the email register behavior that AuthMe has, but adding an email field (additionally to the password field) should be easy.

**Comment by AmazedMender16** [comment]
just would be nice if they can put email and make it case sensitive so it works nice

**Comment by ljacqu** [comment]
hi @AmazedMender16, sample web integration now has an email field for registration. 

You're opening a dangerous door if you want to allow names that only vary in case (user vs. User). This can probably be done by changing `isUserRegistered()` in `AuthMeController` to check the `realname` column instead of `username`. The column needs to have a case-sensitive collation for it to work.
