### ISSUE TITLE
When something is wrong with MySQL, Spigot crashes

### ISSUE THREAD

**Issue by Cysioland** [Xephi/AuthMeReloaded#14]
Hi,
I posted crash log to Spigot, they told me that it's MySQL. After further snooping inside log file, I found your plugin. Please take a look at this.
Crash log: https://gist.github.com/Cysioland/6c7afc0b215ab9b43c7c

**Comment by Xephi** [comment]
Huuum, really strange here :o , i will investigate, is the player already exist in database?

**Comment by Cysioland** [comment]
I don't know, what player are you talking about

**Comment by MrWakeCZ** [comment]
I have same problem Spigot 1649 (1.7.10). http://pastebin.com/cScbPEcD
I think that this problem is in register command because if new player join and write command "/register password password" it crash it. 

[18:50:54] [pool-5-thread-1/INFO]: Creating empty config: /hlserver/27053/plugins/Essentials/userdata/ab700d47-d6a7-3063-b0bb-821d9625d137.yml
[18:51:30] [pool-11-thread-1/INFO]: [CR] Server crashed!, Shutting down

**Comment by sgdc3** [comment]
Still an issue or it's fixed? @Xephi

**Comment by sgdc3** [comment]
Still an issue or it's fixed? @Xephi

**Comment by Trojaner25** [comment]
I can confirm this on 3.5, will test it on the latest 5 Dev

**Comment by sgdc3** [comment]
@Trojaner25 Thank you ;)

**Comment by Trojaner25** [comment]
This may take some time, since it only happens 1x a week or something

**Comment by sgdc3** [comment]
@Trojaner25 @Xephi Fixed?

**Comment by Trojaner25** [comment]
Seems like no crashes happened
