### ISSUE TITLE
Max-Login-Tries

### ISSUE THREAD

**Issue by Trojaner25** [Xephi/AuthMeReloaded#192]
I'd like to request a feature: how often an IP can try to login in a given amount of time.
Because today someone tried to brute-force a staff-account on my server, resulting in a huge chat spam. This was not the first time this happened.

Maybe there should be an option like "auto-ban an IP for X minutes after Y fails of logins"?
(And also please send a notification to the admins online so they can check that ip)

**Comment by Xephi** [comment]
Yeah, why not, actually you can add a ban on bad ip if auth fail and ip isn't the same register in database :') (but really strict and not recommanded for dynamic ip users :'))

**Comment by sgdc3** [comment]
bump

**Comment by ljacqu** [comment]
@Gnat008, a few things I noticed while testing:

- If the IP addr is banned, the player isn't kicked. This is troublesome because the player can still submit login requests as long as he doesn't quit the server (and might even have a successful login request in the meantime).

- The config property comments always speak of "users" (e.g. "How many times a user can attempt to login before being tempbanned") and never of IP. This makes the feature misleading.

- I don't know what @sgdc3 thinks, but for me it is not OK that the failed logins are being counted by username, since it will ultimately have an effect on the IP address. (Evil player tries to log in, gets banned, but then the legitimate player mistypes his password once and he will also get IP-banned.)

**Comment by Gnat008** [comment]
1) I guess I assumed that Bukkit would be smart enough to kick the player at that point. Wrong again.

2) Good point. When I made them I had not thought of IP banning yet. haha

3) True, but then you can likely just restart your modem and get a new IP address. Thoughts?

**Comment by ljacqu** [comment]
Regarding 3), I see your point and I think we should definitely look into this more detailed within the new story you've created, #764. I will post some thoughts on this in there. However, I really don't think counting login fails by name should be in the beta 3 release (which @sgdc3 wants to do soon).

**Comment by Gnat008** [comment]
1 and 2 should be taken care of in latest commit.

**Comment by sgdc3** [comment]
Continued on #764
