### ISSUE TITLE
Permissions login not worked

### ISSUE THREAD

**Issue by Toshka17** [Xephi/AuthMeReloaded#319]
With this permissions http://pastebin.com/XHEXEwsL

Players get the message that they have no permission to use the command /login

Use latest AuthMeReloaded-Dev # 476

**Comment by ljacqu** [comment]
Related: #285
Currently there is no support for the `.*` permissions. I will start working on this today since it's actually an important thing to enable again.

**Comment by Toshka17** [comment]
But in this file has authme.login too

**Comment by ljacqu** [comment]
I'm sorry – I was too quick with my diagnosis of the problem. My point still stands: `*` permissions aren't currently supported (should be in the next 24 hours!) and otherwise, the permission for login is `authme.player.login`. We currently have an up-to-date permissions page at https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md but its location is subject to change.

**Comment by ljacqu** [comment]
Implemented support for `authme.player.*` and `authme.admin.*`; it should be available in the next dev builds.

You can find the most recent list of permission nodes at https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/tools/docs/permission_nodes.md (URL subject to change)

You can find our dev builds at http://ci.xephi.fr/job/AuthMeReloaded-Dev/ **though I would recommend waiting until the build is "blue" again.**

**Comment by ljacqu** [comment]
I'm going to assume that this has been solved. If this is not the case, kindly open another issue with  a reference to this one.
