### ISSUE TITLE
Remove fly in join why?

### ISSUE THREAD

**Issue by andris155** [Xephi/AuthMeReloaded#355]
Authme 5.2 build:185 Snapshot remove fly mode join.
How to disable?

**Comment by sgdc3** [comment]
Can you post your config.yml

**Comment by andris155** [comment]
http://pastebin.com/BF9cYfwY

**Comment by andris155** [comment]
https://youtu.be/diCVKZn6Sxk
Fly remove: 2:00

**Comment by zhgt** [comment]
It happens exactly the same!

**Comment by games647** [comment]
It should be restored by this: [restoreMethod](https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/login/ProcessSyncronousPlayerLogin.java#L169).

By using the IDE debugger I found out that this code doesn't won't execute, because [limbo is null](https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/login/ProcessSyncronousPlayerLogin.java#L142).

**Comment by andris155** [comment]
Latest dev build not fixed bug.

**Comment by ljacqu** [comment]
I'll have a look at this

**Comment by DardBrinza** [comment]
Where fix?

**Comment by ljacqu** [comment]
None yet

**Comment by ArcasCZ** [comment]
In last build still doesn't work for me...

**Comment by games647** [comment]
So you aren't allowed to fly after login?

**Comment by ArcasCZ** [comment]
Nope, i need to use /fly or /gm s -> /gm c

**Comment by ArcasCZ** [comment]
https://ctrlv.cz/shots/2016/01/01/Ti15.png - here is error that I get when I use /tp player [essentials]

**Comment by sgdc3** [comment]
@ArcasCZ please, open a new issue

**Comment by DNx5** [comment]
he is downloaded the wrong build :laughing:

**Comment by ArcasCZ** [comment]
Yep - someone has to fix that link in Readme ;)

**Comment by sgdc3** [comment]
Yeah now i deleted the other jenkins build ;)

**Comment by ljacqu** [comment]
Thanks, @sgdc3!

**Comment by sgdc3** [comment]
@ArcasCZ @andris155 any news about THIS issue? ;)

**Comment by andris155** [comment]
Fixed Thanks!
