### ISSUE TITLE
Wurst hack Authme tutorial

### ISSUE THREAD

**Issue by DardBrinza** [Xephi/AuthMeReloaded#401]
Hi, i found hack-tutorial: https://www.wurst-client.tk/forceop-tutorial/#/title
How protect for this?

**Comment by ljacqu** [comment]
- AuthMe has a **captcha feature** (`max login tries before captcha` setting) that prevents such automatic attacks, since it requires user input and thus halts any automatic script sending passwords. It also helps to keep an eye out for admin usernames logging on from the same IP address. Brute force attacks will typically be well visible within your logs because they will send dozens of tries to the server.

I used to help run an offline server, and we did the following:
- Everyone was **regularly informed** that such attacks happened, and we always briefly explained why it was important not to use one's username or the server's name as password.
- **Force staff to use strong passwords.** We enabled outputting passwords in the logs (I don't necessarily suggest that) and the two of us who had access to the server logs ensured that our staff had sufficiently safe passwords or we would have sent them a message.
- **Set up a fake staff wall near spawn.** Our spawn has a list of admins with a shortened version of their usernames, e.g. "bobby" as "bob", or "myStaffBuddy" as "myStaffBud". Register those passwords with a strong password, and the attacker will be busy trying to get into the wrong accounts. Also super **easy to search the logs for those fake usernames** to find IP addresses of attackers (you can use AuthMe or Essentials commands to see the last IP address that logged on).

I'm particularly proud of the last one. It was really effective. And this way players also knew that it was not an admin. We always told players to make sure an admin is logged IN before giving him stuff etc. but this never really got through to the younger players. It was easier to explain to them: "Look, this is myStaffBud, but that's another name than myStaffBuddy"

**Comment by ljacqu** [comment]
Sorry, I didn't mean to close this. I hit the button on accident.

**Comment by DNx5** [comment]
from what i read, that was some kind of brute force method.
@ljacqu maybe we can add some delay to use login command?

**Comment by sgdc3** [comment]
no, we already have kick on wrong password

**Comment by sgdc3** [comment]
we can add a temp ban/banip if the user fails to login more then x times

**Comment by ljacqu** [comment]
AuthMe has a few things in its tool box to counter brute-force attacks:

- Captcha feature. The limit for showing a captcha can be quite low here (e.g. 3). What might be nice is an option to display the captcha more frequently after many bad login attempts, e.g. "display catcha after 5 login tries, and then after every 2 login tries."

- Fantastic idea about the temp banip! (I think IP might be better, otherwise I can easily temp ban my enemy's account by just entering a wrong password a few times in his name). Just need to make sure that the threshold is high enough (at least 12).

But this brute-force thing is not new to you, right? I've been seeing that on "my" server for almost two years now.

**Comment by GeARCraft1** [comment]
I will test it on my server, then i send the log.
