### ISSUE TITLE
[BUG] Flat To MySql

### ISSUE THREAD

**Issue by DoomGary** [Xephi/AuthMeReloaded#457]
Is there any way to change them? Already did with the /converter and gave me this file: http://pastebin.com/1nHzuVCs Already tried to import them, nothing happen

**Comment by sgdc3** [comment]
Yeah this sql file is empty.

**Comment by ljacqu** [comment]
@DoomGary How did you do flat to mysql? What `/converter` command exactly? (NB: It's `/authme converter` now). Because I don't think we offer Flat to MySQL directly. I made some changes to ForceFlatToSql that would allow us to implement it easily, though.

**Comment by ljacqu** [comment]
Come to think of it, since we force conversion from flat to SQLite it doesn't make sense to create flat to mysql because you'll never have the opportunity to execute the command. That means one has to go through the mandatory conversion from flat to SQLite and then execute the SQLite to MySQL conversion.

@DoomGary Does this solve this issue?

**Comment by sgdc3** [comment]
@ljacqu Yeah, you're right

**Comment by sgdc3** [comment]
@DoomGary Any news?
