### ISSUE TITLE
Run a custom command when more than x alts are detected.

### ISSUE THREAD

**Issue by Done84** [Xephi/AuthMeReloaded#459]
Hello. It would be nice if besides being able to see accounts registered in the same ip we could also run a custom command when this happens.
Basically and option like:

If player/IP has more than X accounts run this command
- /command %playername something

The X amount could also be configurable. Its very easy for players to override the max allowed registrations by using a VPN or a friends pc or another internet connection, this would allows us to take some actions when this happens.

**Comment by Done84** [comment]
Upps forgot tot tittle my enhancement. - Run a custom command when more than x alts are detected.

**Comment by sgdc3** [comment]
@Done84 do you need to do the check on player join or while logging in and/or registration

**Comment by Done84** [comment]
Would be nice if the check would run on login since the attention span of the the regular player is short.

**Comment by sgdc3** [comment]
Ok, i'll try to do that today ;)

**Comment by sgdc3** [comment]
Done! ;)

**Comment by ljacqu** [comment]
Regarding this code bit:
```java
        if(threshold <= 1 || command.isEmpty()) {
            return;
        }

        if (auths.size() >= threshold) {
            return;
        }

        bukkitService.dispatchConsoleCommand(command
            .replaceAll("%playername%", player.getName())
            .replaceAll("%playerip%", ip)
);
```

- The config comment says "Threshold of the other accounts command, a value less than 1 means disabled." but the code checks for `threshold <= 1`, which includes 1. 1 itself probably doesn't make sense, so should the comment be adjusted?
- +1 for adding the variables to the command setting, but I'd wager "The other accounts command" doesn't tell the user when this command is run. Maybe something like "Command to run when a user has more accounts than the configured threshold"?

- On a side note, you generally want to write positive `if` statements instead of `return`-ing out of a method. This makes it clearer when exactly the command is executed (I don't need to keep track of all the conditions that trigger a `return`) and it's less of a "trap" in case we add something below to be run in all cases.

**Comment by sgdc3** [comment]
> The config comment says "Threshold of the other accounts command, a value less than 1 means disabled." but the code checks for threshold <= 1, which includes 1. 1 itself probably doesn't make sense, so should the comment be adjusted?

It'a a previous version of the code, I forgot to update the local git repo before pushing, sorry

**Comment by ljacqu** [comment]
@sgdc3 No problem! If you need any help here please let me know.

**Comment by sgdc3** [comment]
I completely forgot about this, i'l try to close this asap.

**Comment by sgdc3** [comment]
> The config comment says "Threshold of the other accounts command, a value less than 1 means disabled." but the code checks for threshold <= 1, which includes 1. 1 itself probably doesn't make sense, so should the comment be adjusted?

Yes, it should

**Comment by sgdc3** [comment]
> Maybe something like "Command to run when a user has more accounts than the configured threshold"?

Yeah, I have no fantasy xD

**Comment by sgdc3** [comment]
> if (auths.size() >= threshold) {
            return;
        }

This is wrong

**Comment by sgdc3** [comment]
Ok, should be correct now ;)
