### ISSUE TITLE
sql warning

### ISSUE THREAD

**Issue by RoinujNosde** [Xephi/AuthMeReloaded#469]
Hello,
I started using the last build (699) and i'm getting this warning on console/log:
[AuthMe] [SQLITE_CONSTRAINT]  Abort due to constraint violation (column username is not unique)

Should i worry about it?

(Server version: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT))

**Comment by games647** [comment]
Could you post the complete error?

**Comment by RoinujNosde** [comment]
That's the complete error.

**Comment by sgdc3** [comment]
wtf? duplicated username column?

**Comment by ljacqu** [comment]
Can you post some of the surroundng lines in the log?
Did this happen when someone tried to /login or /register?

**Comment by ljacqu** [comment]
In MySQL.java:
```

                + columnName + " VARCHAR(255) NOT NULL UNIQUE,"
                + columnRealName + " VARCHAR(255) NOT NULL,"
```
columnRealName should be UNIQUE—not columnName. This probably happened when someone registered "Bobby" and then later "bobby"

**Comment by RoinujNosde** [comment]
Server log: [2016-01-24-4.txt](https://github.com/Xephi/AuthMeReloaded/files/103390/2016-01-24-4.txt)
This warning seems to occur when someone joins the server.

**Comment by RoinujNosde** [comment]
Hello?

**Comment by ljacqu** [comment]
Sorry. I will take care of this.

**Comment by RoinujNosde** [comment]
>> This probably happened when someone registered "Bobby" and then later "bobby"

**Comment by ljacqu** [comment]
With a setting, we allow the same nick to be registered in different casing, i.e. "nick", "Nick", "NICK". That's why we have a `username` and `realname` column (named somewhat confusingly), where `username` is always lowercase and `realname` contains the correct casing. So it is possible—in theory—to have the following in the DB:

```
username | realname
-------- | -------
nick     | nick
nick     | Nick
```

Currently we tell the DB that `username` should be unique, but it should be `realname`, of course.

Allowing different casings of the same name is a terrible idea:
1) Other plugins deal with it poorly
2) I'm not even sure we fully support it...

I will quickly finish another MySQL issue and I'll take a closer look at this. I think there are places where we rely on getting player information from the lowercase name, which obviously causes trouble for the "Nick"/"nick" scenario.

---

A question for you, @RoinujNosde: Do you have such username registrations with different casing? I looked at the log and this error always appears, but users seem to log in successfully. Is that correct?

**Comment by sgdc3** [comment]
@ljacqu Look at this: https://gist.github.com/lahwran/1188500
We can change the player name and displayname on join to match the realName

**Comment by sgdc3** [comment]
The only issue is that we need access to NMS code

**Comment by RoinujNosde** [comment]
@ljacqu I don't have this kind of registration. I was using AuthMe 3.5-SNAPSHOT and when you join with a different case, it asks you to use /login.

> I looked at the log and this error always appears, but users seem to log in successfully. Is that correct?

Only one person (me) logged in, whitelist was on.

**Comment by sgdc3** [comment]
@ljacqu What do you think about the setname solution?

**Comment by ljacqu** [comment]
@sgdc3 Hmm, that's very interesting. I do have mixed feelings, though, what the code does is call `Player#setDisplayName()`—but there's also `Player#getName()`. Plugins go through `Player#getName` to identify players so I'm not sure if this solves the problem.

--

@RoinujNosde I had a closer look at the log. There was a conversion from flatfile to SQLite, which seems to have gone fine. I was thinking maybe in the flatfile there was the same multiple times that would have caused problems during the migration, but it seems to have gone fine... :/

It seems that this exception is being logged in `AuthMePlayerListener#onPreLogin` because we make a DB call to get user info. I guess if the unique constraint is violated then the DB will complain. I would wager that the DB _always_ returns this exception even when the user we're trying to look up isn't duplicated.

Unfortunately at this point we need somehow to be able to duplicate this to find out the cause, whether it comes from flatfile conversion or something else. It's a lot to ask, but could you perhaps mail me your authme.db file? My email is my github username @hotmail.com

Maybe @games647 @DNx5 have another idea as to what is happening?

**Comment by sgdc3** [comment]
@ljacqu Look at https://gist.github.com/lahwran/1188500#file-changeplayername-java-L42

**Comment by sgdc3** [comment]
player.setDisplayName(args[0]); set the tablist/chat name
setPlayerName(player.getHandle(), args[0]); the real nickname (very hacky code)

**Comment by RoinujNosde** [comment]
@ljacqu email sent.

**Comment by ljacqu** [comment]
@sgdc3 Sorry, I missed that :P

@RoinujNosde Thank you; I got it :) I'm looking into it. I did some queries on the SQLite db and didn't find anything... so now I'll try the migration and I'll see how that goes. I'll keep this thread updated

**Comment by RoinujNosde** [comment]
@ljacqu Beleza.

**Comment by ljacqu** [comment]
@RoinujNosde I could perform the flatfile to sqlite conversion with no error, and after that running the server with the sqlite database works fine for me. Also running the server with the SQLite db you provided me.

Therefore, I would like to suggest updating your AuthMe version with one of the latest builds, hopefully that helps. http://ci.xephi.fr/job/AuthMeReloaded/

I updated the error logging in our SQLite handling today, so if you update version and the error still happens, maybe we can see a better (longer) error in authme.log (if you have `logConsole: true` in config.yml)

**Comment by RoinujNosde** [comment]
Warning is gone with build 793.

**Comment by sgdc3** [comment]
Ok, should have been fixed, we'll reopen this issue if the problem persists.
