### ISSUE TITLE
[Dev] Too many active branches.

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeReloaded#485]
Please delete/merge some of them. Thanks ;)

**Comment by sgdc3** [comment]
Woops it assigned the issue to ljacqu itself xD

**Comment by ljacqu** [comment]
https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

Branches are very lightweight. I (still) don't understand the issue with having more than like two (because this seems to come up every now and then). I can only speak for the branches I've started but there I promise that they're being looked after ;)

**Comment by ljacqu** [comment]
Maybe this issue can be closed now.

**Comment by sgdc3** [comment]
@ljacqu Lol! Forgot about that ;)
