### ISSUE TITLE
[Suggestion] Op password 

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#502]
Hello!

I have a suggestion :p

What do you think about lock the op command? :)
for example: the command is the folowing: /op &lt;player> &lt;password>

**Comment by ljacqu** [comment]
(Note: edited `<` to `&lt;` in the issue description because typing things like `<player>` will be interpreted as HTML otherwise)

**Comment by sgdc3** [comment]
This should be handled by another plugin

**Comment by ljacqu** [comment]
Thanks for the suggestion, @rErEaT—I agree with @sgdc3. What you can do is rename the /op (and /ban etc.) commands in your server config file so that they do something else.
The server I used to maintain had /eop, /eban (besides /eop Essentials already provides these e-commands) and we redirected /eop, /eban to a trivial command no one had permission for (namely /ptime). So for the user it looked like he literally had no permission for the regular command ;) 

See also #401 for some safety tips
