### ISSUE TITLE
Cannot invoke size() on the array type Player[]

### ISSUE THREAD

**Issue by anchoretics** [Xephi/AuthMeReloaded#58]
hi~

when i use git clone the master,build in my eclipse,
there are some errors "Cannot invoke size() on the array type Player[]" in AuthMe.java,etc...
then i review the code, found that in brunch 4.0,the code in AuthMe.java and line 450 is:
      Bukkit.getOnlinePlayers().length != 0
but in the master's AuthMe.java line 456 is:
      Bukkit.getOnlinePlayers().size() != 0 
i know that Bukkit.getOnlinePlayers() returns a Array,the array can be only count by length property,
so the question is why use Bukkit.getOnlinePlayers().size()??

**Comment by anchoretics** [comment]
I think it's my faults, the master brunch is 5.0 version , and my bukkit server is 1.7.9, and in 
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/files/  there is version 3.5 for server 1.7.9, 
so where is the souce code for v3.5 ? is brunch 4.0 can be used in 1.7.9?

**Comment by Xephi** [comment]
branch 4.0 is not safe for use and will be removed

**Comment by Trojaner25** [comment]
This is caused by an outdated craftbukkit build. This commit: https://github.com/Bukkit/Bukkit/commit/0d9771acf6e59ca77fea3f55a33508661bcf7a5d on newer builds changed the behaviour of getOnlinePlayers(). It doesn't return a Player[] array anymore, instead a Collection<? extends Player> is returned. This version of AuthMe seems to call getOnlinePlayers() and excepts the new Collection instead of an array, so it uses size(). But since the old craftbukkit versions only return an array, they dont have the size() method.

A simple fix is available (requires a wrapper method):
https://bukkit.org/threads/code-snippet-workaround-for-the-new-bukkit-getonlineplayers-method.285072/

**Comment by Xephi** [comment]
Fixed also https://github.com/Xephi/AuthMeReloaded/commit/4e75fb76d0cc8b971922c3ce206469df7a7d2567

**Comment by anchoretics** [comment]
ok，i will use the master branch.
so i modified the code, and rebuild it for my Bukkit version 1.7.9-R0.2, it works!
