### ISSUE TITLE
hidetablist error

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#641]
Its working but the players doesnt see her ranks on the tab.

(I am using AnimatedNames)
But everyone see the others ranks :D

**Comment by sgdc3** [comment]
Anyone can see others rank but not his own, right?

**Comment by rErEaT** [comment]
yes

**Comment by sgdc3** [comment]
@games647 Could you please check if we can do something to avoid this? ;)

**Comment by games647** [comment]
Does it work if the player goes away (teleport away or vanish) and comes back?

**Comment by rErEaT** [comment]
no :(

**Comment by games647** [comment]
Then I think it's impossible, because currently the things on a scoreboard are associated to the names which are not visible when the client joins. We would be forced to cache the sent scoreboard packets and resend them after the player logged in. I don't think this is a good idea. So the only option is to disable the hideTablist feature in the config of AuthMe.

**Comment by sgdc3** [comment]
@rErEaT You should ask the developer of the prefix plugin to listen to our LoginEvent in order to re-set the player's tablist name. ;)

**Comment by rErEaT** [comment]
oh okay :/
