### ISSUE TITLE
[Suggestion] Bypass the purge with permission

### ISSUE THREAD

**Issue by rErEaT** [Xephi/AuthMeReloaded#674]
I think its would be nice if I can add a permission to my staff group whos accounts never purged then :)

**Comment by ljacqu** [comment]
Would a list of names also be a possibility? I think it would be easier to implement.

**Comment by rErEaT** [comment]
hmm not bad, but I think the permission is would better because the player names can changed

**Comment by sgdc3** [comment]
+1 permission ;)

**Comment by rErEaT** [comment]
but If u can create it for usernames, that would be nice also:)

**Comment by sgdc3** [comment]
@ljacqu @games647 in order to accomplish this we need a way to check the permission of an offline player with a certain nickname. Should we add it to the perm manager?

**Comment by ljacqu** [comment]
One question I have for this is how many perm managers support this. 
There's a refactoring story for the perm manager that would go lovely with this btw, but it's a big one

**Comment by sgdc3** [comment]
almost every perm manager has a deprecated pre uuid method

**Comment by ljacqu** [comment]
In that case - sounds good! Can I have until the weekend to do some refactoring on the perms manager? It's one huge block of code that needs to be structured a little. Seems like I can't interest anyone into refactoring it :P

**Comment by rErEaT** [comment]
so what happend? :D

**Comment by Gnat008** [comment]
@ljacqu, I started work on this tonight, but I feel that it would be better to refactor the purge task into a whole process, since this touches the databases as well. @sgdc3 and I would like your input on that. I started permissions work on a new branch that has this issue number in it.

**Comment by ljacqu** [comment]
Lovely, @Gnat008! From a quick glance, it seems you probably need an additional service class (as you mention) but probably the PurgeTask class needs to stay. It schedules itself with the BukkitScheduler, and we don't want a service class itself to start scheduling itself.

Are you familiar with how the PurgeTask works? The trick behind it is it handles a certain portion of players in an interval, to avoid overloading the server's resources.

**Comment by Gnat008** [comment]
Yeah, I noticed that. Pretty nice, really.

**Comment by ljacqu** [comment]
Great work @Gnat008, we're one feature richer and you even rid us of some technical debt in the process :) :+1: I'm especially impressed that you took the time to implement the offline permission lookup for each handler!

A few q's about the permissions:
- Could we rename `PermissionsManager#hasPermission(String, PermissionNode)` to reflect that it's for offline players? It shares the same name with `hasPermission(Player, PermissionNode)` now, which I find misleading (feel free to disagree).
- For offline player permission lookups, should the default permission be considered? Currently always defaults to `false` if no handler available. (I don't find it necessary to look up if an offline player is OP, but I'd expect that a permission node with ALLOWED as default will fall back to `true`.)

The purge process:
- Bit unfortunate we have to duplicate the logic for autorun / regular run (as we did before your refactoring). If you agree I'll look if this can somehow be merged a little; I want to write tests for the PurgeService anyway.

Finally, just a remark: we don't support FlatFile anymore so that logic in there will never come into play. When the `DataSource` interface changes we typically just implement the method with a `throw new UnsupportedOperation()`...

**Comment by ljacqu** [comment]
Oh, one last thing—call me pedantic, but you created `PermissionsManager#getHandler` to get the permission system type. Would it be possible to remove this and to have a `getPermissionSystem()` method on PermissionsManager itself? This way we don't expose the entire permissions outside of PermissionsManager.

It will return `null` when there is no handler, so in AuthMe:
`permsMan.getHandler().getPermissionSystem() == PermissionsSystemType.PERMISSIONS_BUKKIT` will have to be changed to `PermissionsSystemType.PERMISSIONS_BUKKIT.equals(permsMan.getPermissionSystem())`.

**Comment by Gnat008** [comment]
With the permissions, absolutely agreed on both. I just wasn't sure what to name the method otherwise (naming.. heh). Also checking the default permission is a good thing and I probably should have done that.

I'm also unhappy with the duplicate logic for the same reason. If that could be made better, it should.

I implemented the FlatFile thing as well since it implements the interface, and I guess it seemed like a good idea at the time? Probably just made more work for myself doing it, but oh well. lol

**Comment by ljacqu** [comment]
@Gnat008 I tested the changes and pushed them to master. If you think this issue can be marked as "please verify," please do so. If you no longer need the 674 branch it can be removed. Thanks!

**Comment by Gnat008** [comment]
@rErEaT :)

**Comment by rErEaT** [comment]
@Gnat008 what is the permission to bypass from purge? :)

**Comment by Gnat008** [comment]
@rErEaT authme.bypasspurge

**Comment by rErEaT** [comment]
thanks, I am checking it :)

**Comment by sgdc3** [comment]
@rErEaT so? ;)

**Comment by rErEaT** [comment]
its just purge the authme database right?
I have 5k essentials userfiles and max 100-200 in use :/

**Comment by sgdc3** [comment]
let's give it a try ;)

**Comment by ljacqu** [comment]
@rErEaT Could you run it successfully?

**Comment by rErEaT** [comment]
Does not delete the default world's player data :/

**Comment by ljacqu** [comment]
Could I ask you to open a new issue for this, please? Then we can keep this issue title/number for "implement bypass permission" and we'll have a new issue for "purge does not delete player data." I'm assuming you mean the .dat files of a player are not being deleted?

**Comment by sgdc3** [comment]
Open a new issue, please ;)
