### ISSUE TITLE
Can't Undo blacklist country

### ISSUE THREAD

**Issue by tuanjr** [Xephi/AuthMeReloaded#675]
So, example: i added US to blacklist country, nextime, i removed US from blacklist, but players from US still can't login server. i try to add US to protected country list, player still can't login. Try /authme reload, restart server, reset player's modem....still won't work. i dont known why!

**Comment by ljacqu** [comment]
I'm going to see if I can reproduce this, and I'll report back.

In the meantime: are you sure that the country whitelist is empty? If there is a whitelist, the blacklist will be ignored and only countries of the whitelist will be admitted. So if the US is missing from there, players from the US will be rejected.

**Comment by tuanjr** [comment]
`Protection: 
    # Enable some servers protection (country based login, antibot)
    enableProtection: true
    # Countries allowed to join the server and register, see http://dev.bukkit.org/bukkit-plugins/authme-reloaded/pages/countries-codes/ for countries' codes
    # PLEASE USE QUOTES!
    countries: 
    - 'VN'
    - 'JP'
    - 'KR'
    - 'O1'
    - 'US'    
    # Countries not allowed to join the server and register
    # PLEASE USE QUOTES!
    countriesBlacklist:
    - 'A1'    
    # Do we need to enable automatic antibot system?
    enableAntiBot: true
    # Max number of players allowed to login in 5 secs before the AntiBot system is enabled automatically
    antiBotSensibility: 20
    # Duration in minutes of the antibot automatic system
    antiBotDuration: 5`

this is my config. it's correct?

**Comment by ljacqu** [comment]
@tuanjr Looks good. Maybe the user you expect to be able to join is from `A1` for some reason? Otherwise there is no reason for it not to work.
I did some code clean up for the way we handle the countries and tested it afterwards. Changes to the settings + `/authme reload` immediately apply, so if I could ask you to use build n. 964 or upwards: http://ci.xephi.fr/job/AuthMeReloaded/
If the problem persists, we'll have to troubleshoot

@sgdc3 @DNx5 One change to my commit: the "enable protection" setting decides whether the country whitelist and blacklist comes into play. Before, that setting only determined whether the blacklist was being considered, which I didn't really understand the purpose of. Please let me know if this had an intention behind it and I'll adjust it.

**Comment by tuanjr** [comment]
I will try new build and report back, thank you!

**Comment by sgdc3** [comment]
@ljacqu I think @Xephi 's purpose was to keep the A1 (proxy) protection active by default

**Comment by ljacqu** [comment]
@tuanjr Thanks!
@sgdc3 That makes sense, so I will change it to `enableProtection && hasWhitelist() ? checkWhitelist() : checkBlacklist()`.

Actually does this Protection.enable thing make sense? It enabled/disables an odd mix of features (country whitelist, antibot, ...)

**Comment by sgdc3** [comment]
We should make an enable setting for every protection feature

**Comment by ljacqu** [comment]
@sgdc3 I wonder if it is intuitive to have the blacklist always enabled and the whitelist depend on another setting. As per your comment I could imagine two things:
```
# comment with example -> default value empty
countryWhitelist: []
# blacklist 
countryBlacklist:
- 'A1'
```

```
enableCountryWhitelist: false
countryWhitelist:
- 'US'
- 'GB'
countryBlacklist:
- 'A1'
```

I'm not very fond of the latter (I have values in my whitelist but they don't work?) but I'll let you decide

**Comment by ljacqu** [comment]
`OnJoinVerifier.checkPlayerCountry` checks for the "enable protection" setting -> this can be closed, all open ends are finished.
