### ISSUE TITLE
Wrong password after update (Mysql and PlainText)

### ISSUE THREAD

**Issue by agusztin** [Xephi/AuthMeReloaded#683]
1) Have installed this version of AuthMe: AuthMe 5.0-SNAPSHOT (AuthMe-5.0-beta3.jar)
2) In AuthMe config.yml have this settings:
passwordHash: PLAINTEXT
supportOldPasswordHash: true
3) Login with my account called: "Test" the password of "Test" is: "Pedro"
Everything is ok at this moment.
But when i update.
4) Install the last dev build version of AuthMe: http://ci.xephi.fr/job/AuthMeReloaded/957/
5) Log with my account "Test" and the password "Pedro"
6) Wrong password.

**Comment by ljacqu** [comment]
Plaintext is no longer supported but should be converted to our salted SHA-256 implementation.

In your config.yml, is the hash algorithm changed to SHA256?
In your datasource, what is the value in the password column?
Are there any errors or WARN-level messages in authme.log?

**Comment by agusztin** [comment]
Plaintext is no longer supported but should be converted to our salted SHA-256 implementation.
I know this, i see the message in console.

In your config.yml, is the hash algorithm changed to SHA256?
Yes.

In your datasource, what is the value in the password column?
https://i.gyazo.com/b5ef7e8a3acacae6812987919509991f.png 
(Please tell me when i can delete the image)

Are there any errors or WARN-level messages in authme.log?
No.

**Comment by agusztin** [comment]
Can you help me?
I need to recover that database.
Realy need help with this, i dont want to lose my database.
I can pay for support.

**Comment by ljacqu** [comment]
You can delete the image again if you want. I was particularly interested in your "Test" case with password "Pedro", since we could then confirm whether the hash is correct or not. Otherwise all I can tell you from that picture is that the format seems to match our SHA hashes, nothing out of the ordinary.

Did you maybe revert to 5.0 with PLAINTEXT and run the migration _again_ on what were already SHA-256 hashes? In that case the passwords/hashes cannot be recovered to a useful state.

**Comment by agusztin** [comment]
Sorry for my english, i speak spanish.

I have more than 300.000 accounts in the database. (I think.)
In my case i did an error.
When the plugin AuthMe (AuthMe-5.2-SNAPSHOT-spigot.jar ) run the process of migration the accounts from PLAINTEXT to SHA-256, the console stop working. the console was "frieze" and i forced to stop the server (ctrl + D A in Linux)  
And i start the server again but this time let the migration process ends.
After all this confusion i have the problem of "wrong password"
You understand?

There is possibilities to recover my AuthMe database after this confusion?

**Comment by ljacqu** [comment]
I'm afraid this sounds like the passwords were hashed twice with our SHA-256 implementation. We use random salts to them, so without knowing the initial one, there is no way to actually check the correctness without brute-forcing into oblivion. Hopefully you have a backup.

---

If you want to know the details, our SHA-256 hash does the following:
```java
salt := random string of 16 chars
hash := "$SHA%" + salt + "$" + sha256(sha256(password) + salt)
```

There's no way to compute back the password from the resulting hash. To check if a password matches, we just hash again with the same salt and check if the hash is the same.
So if the above is done twice, the only way the password could be recognized, is if we could first hash with the first salt, and then hash with the second salt.
Since the first salt is stored in the same block of text, we don't know the first salt anymore.

**Comment by agusztin** [comment]
I don't have backup.
I do not quite understand your answer but I think there is no solution.
No problem, i am going to reset my database.
Survived more than 3 years.

Just add a warn message telling that the plugin AuthMe is going to migrate accounts and the console maybe freeze. or something like that ok?

**Comment by EvilOlaf** [comment]
You run a server for three years without running backups?

**Comment by ljacqu** [comment]
@agusztin I'm sorry man. I would still suggest to keep the database—those who set an email can reset their password, and for the others you can easily check that they are legit by comparing the IP addresses and then resetting their passwords. If you have a forum you can have them msg you for a new password on there. Remember the last login date when this happened & then you can easily tell accounts with new, valid passwords apart from "dormant" accounts.

Is a message like the following what you suggest?
> Your HashAlgorithm has been detected as plaintext and is now deprecated; it will be changed and hashed now to the AuthMe default hashing method

**Comment by agusztin** [comment]
I see that message in the console but i think a message like this:

> Your HashAlgorithm has been detected as plaintext and is now deprecated; it will be changed and hashed now to the AuthMe default hashing method
> Don't stop your server, wait for the convertion. 

or a message like that.

**Comment by ljacqu** [comment]
@agusztin Thanks for your input. I added the message and also changed the conversion to skip any hashes starting with $SHA$ so we shouldn't ever double-hash any entries anymore.
If this concludes this issue, kindly close it; or please let us know what we can still do for you.
