### ISSUE TITLE
Wrong /login usage message 

### ISSUE THREAD

**Issue by EendyGame** [Xephi/AuthMeReloaded#758]
How to disable /login message

http://s8.hostingkartinok.com/uploads/images/2016/06/f44f2926619c2447c69e92674f5dd1d1.png

**Comment by sgdc3** [comment]
why?

**Comment by EendyGame** [comment]
http://s8.hostingkartinok.com/uploads/images/2016/06/71c3cedac897af7ee8b2f6623b199ef9.png

custom message in message.yml :)

**Comment by EendyGame** [comment]
help me?

**Comment by sgdc3** [comment]
So, you use /login YOURPASSWORD and it shows the message? It seems like a bug.

**Comment by EendyGame** [comment]
no, i'am login and use cmd /login again
how to edit message: http://s8.hostingkartinok.com/uploads/images/2016/06/71c3cedac897af7ee8b2f6623b199ef9.png

**Comment by sgdc3** [comment]
ah ok, it should say : you're already logged in, thats strange

**Comment by EendyGame** [comment]
please...

**Comment by sgdc3** [comment]
@EendyGame Please what? We need to find out why the message is shown.

**Comment by EendyGame** [comment]
i'am recording movies. wait...

**Comment by sgdc3** [comment]
Thanks ;)

**Comment by EendyGame** [comment]
https://yadi.sk/i/KsD9P8bpsRWVA

**Comment by EendyGame** [comment]
https://yadi.sk/i/rLeg99Y0sRWXz

and bug. bungeecord how to fix?

**Comment by sgdc3** [comment]
@EendyGame bungee: ip_foward: true and bungeecord: true on spigot

**Comment by sgdc3** [comment]
The message: we need to add the help strings to the language files ;)

**Comment by ljacqu** [comment]
What needs to be done for this issue? I've identified two things:
- Translatable help strings: will be handled with #293, which is also planned for 5.3 Beta
- Implied suggestion that /login help should be different after player is logged in? Something I don't agree with.

If only the first, I would kindly ask @EendyGame to subscribe to #293 and to close this issue as a duplicate.

**Comment by Twonox** [comment]
Wait... You don't have understand xD
There is `usage_log: '&cUsage: /login <password>'` in messageEN.yml, aslo when we do `/login` or `/l` without password the message usage_log: `'&cUsage: /login <password>'` must be display on chat.
But this message isn't displayed.
The message displayed is: 

> http://s8.hostingkartinok.com/uploads/images/2016/06/71c3cedac897af7ee8b2f6623b199ef9.png

It's wrong message.

**Comment by sgdc3** [comment]
Sorry xD

**Comment by sgdc3** [comment]
Ok this is blocked by the other issue

**Comment by Twonox** [comment]
There is no fix ??

**Comment by ljacqu** [comment]
Will be done in 5.3 Beta

**Comment by sgdc3** [comment]
Done in #293

**Comment by Twonox** [comment]
#293 concerns the translations.
This issue is different, it concerns a wrong sent message.

Instead of that:
http://image.noelshack.com/fichiers/2017/01/1483487429-2017-01-04-004956.png
We receive that:
http://image.noelshack.com/fichiers/2017/01/1483487423-2017-01-04-004858.png

But for register usage this is the right message which is sent:
http://image.noelshack.com/fichiers/2017/01/1483487425-2017-01-04-004942.png
http://image.noelshack.com/fichiers/2017/01/1483487427-2017-01-04-004907.png

**Comment by ljacqu** [comment]
Hello @Twonox @EendyGame—please verify, build n. 1515 or above.

Background:
This is more of an enhancement than a bug. Usually if the arguments of a command don't match what we expect, we show the `/<command> help` page. We can't do that for `/login` because the number of valid arguments depends on various settings (hash algorithm (2FA) and configurable second argument). So for /login we say to the command handler: "both arguments are optional!" and we handle the cases inside of the command code itself.

Now, of course, it makes more sense to send a custom message if we have one, which is the case for the login command as well. So now this is changed to behave that way. Sorry for the wait and for the long back and forth.

**Comment by Twonox** [comment]
It's okay, thank :)

**Comment by ljacqu** [comment]
Thanks!
