### ISSUE TITLE
Player already in game

### ISSUE THREAD

**Issue by MrFiliper** [Xephi/AuthMeReloaded#760]
On server, i have player with name CrazyPlayer. If new player login to the server, with nick Player, Player was kicked, becouse is already in game.

Player = CrazyPlayer? Please, fix this bug. Thanks.

**Comment by Platinteufel** [comment]
AuthMe & Spigot version? ^^

**Comment by sgdc3** [comment]
Not enought infos, please provide the authme version number

**Comment by sgdc3** [comment]
@MrFiliper

**Comment by ljacqu** [comment]
Reopening, as I can confirm. Join server with a name, open another client with same name and it will let you join and kick the first connection.

**Comment by Platinteufel** [comment]
Confirmed too.
ForceSingleSession seems to be broken atm.

# When this setting is enabled, online players can't be kicked out
# due to "Logged in from another Location"
# This setting will prevent potential security exploits.
ForceSingleSession: true

**Comment by Platinteufel** [comment]
@ljacqu Here's the build that causes the issue: http://ci.xephi.fr/job/AuthMeReloaded/1068/

**Comment by MrFiliper** [comment]
Sorry for late response.

AuthMeReloaded v5.1-SNAPSHOT! 
Spigot 1.8.8 Build 201511280430, development

**Comment by sgdc3** [comment]
@ljacqu you can't check the single session in the login event! You need to check it in the prelogin event!

**Comment by ljacqu** [comment]
I only partly agree—doing the check in the PlayerLoginEvent should work, too. onPreLogin isn't fired on CraftBukkit. 
I'll step through the code and test with Spigot and CraftBukkit this evening.

**Comment by sgdc3** [comment]
@ljacqu It's strange, the PreLoginEvent exist in craftbukkit.

**Comment by ljacqu** [comment]
@MrFiliper @Platinteufel—please verify with build n. 1129 or upwards, http://ci.xephi.fr/job/AuthMeReloaded/1129/. Thanks to @MrFiliper for the initial report, and to @Platinteufel and @sgdc3 for the analysis.

Background:
Before a player joins a server, two events are fired which can be caught and modified to disallow the player from joining. Unfortunately, CraftBukkit does not fire one of those events—the PlayerPreLoginEvent—so I moved most of the logic to the other event. Turns out that it is imperative to check the single session in the PlayerPreLoginEvent. This means the single session feature is not supported for CraftBukkit (it's fine on Spigot).

**Comment by Platinteufel** [comment]
Fix verified, thanks @ljacqu

**Comment by sgdc3** [comment]
@ljacqu Not true as the singlesession feature exists since before the first spigot release.

**Comment by sgdc3** [comment]
Ok, that's because before 4.0 authme was using only the PlayerLoginEvent ;)
https://github.com/AuthMe-Team/AuthMeReloaded/blob/3.4/src/main/java/fr/xephi/authme/listener/AuthMePlayerListener.java#L380

**Comment by ljacqu** [comment]
@sgdc3 there was a change around 1.8, https://hub.spigotmc.org/jira/browse/SPIGOT-968
