### ISSUE TITLE
Wrong login coordinates

### ISSUE THREAD

**Issue by Eufranio** [Xephi/AuthMeReloaded#846]
When a player leave the server (going to the nether, by example, and gets timed out), when he joins again the server, he's in the overworld, something like a rollback happens.

**Comment by ljacqu** [comment]
So you have `saveQuitLocation` (or similar, on mobile atm) set to `true`?

**Comment by sgdc3** [comment]
@Eufranio

**Comment by Eufranio** [comment]
@ljacqu i have it set to false.

**Comment by sgdc3** [comment]
@Eufranio Could you post your config?

**Comment by ljacqu** [comment]
I can't reproduce it. I also set `saveQuitLocation: false`, teleported to the nether, logged out (even force-closed the client instead of quitting properly) and next time after logging in successfully I am back where I left. I can join, not log in, and next time I join and log in I will be back in the nether. Same for being kicked... I just can't reproduce this with my setup on Spigot 1.8.8.

**Comment by Eufranio** [comment]
Here's my config: http://pastebin.com/hS8hBt0M
Also, i'm running it on 1.7.10, with Thermos (kCauldron fork).

**Comment by sgdc3** [comment]
@Eufranio still happening?

**Comment by Eufranio** [comment]
Yes, still happening,

**Comment by Twonox** [comment]
If saveQuiteLocation is set false it's not normal if the spawn location is not saved ?
I have also tested with saveQuitLocation true and false but nothing change, it's not normal, is it ?

**Comment by Twonox** [comment]
If you remove Authme there is same problem ?

**Comment by Eufranio** [comment]
If i remove AuthMe it works.

**Comment by Twonox** [comment]
Do you have tested latest dev build ?

**Comment by sgdc3** [comment]
This is the latest build, the 1.7.10 version:
http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.2-SNAPSHOT-legacy.jar

**Comment by Eufranio** [comment]
Fixed using the legacy.
