### ISSUE TITLE
NewAPI can no longer be retrieved

### ISSUE THREAD

**Issue by Sitmobedaf** [Xephi/AuthMeReloaded#873]
http://pastebin.com/kAdBjpfY

**Comment by sgdc3** [comment]
Not our fault :/ Can't see any reference to authme in the stacktrace

**Comment by sgdc3** [comment]
Ah found it, ChatGuard developer needs to recompile the projevt with latest version of our api.

**Comment by ljacqu** [comment]
We had two constructors for NewAPI, one removed in https://github.com/AuthMe/AuthMeReloaded/commit/b671c94e0b0ce902cb823c37d64fd332ae123bc2 because we always call the other one on initialization. Turns out the one I left doesn't register the instance... :pensive: (ouch)

Thank you for reporting this issue—fixed with build nr. 1235 & above. http://ci.xephi.fr/job/AuthMeReloaded/.

**Comment by Sitmobedaf** [comment]
Fixed, thanks.
