### ISSUE TITLE
Login fail tempban issue

### ISSUE THREAD

**Issue by Twonox** [Xephi/AuthMeReloaded#876]
Failure count for /login is not reseted after right login. Then if a player fail 9 logins, successful tenth login and fail 1 login another time, he is tempbaned... (if limit is 10 logins)
There is false bans for my players :/

**Comment by sgdc3** [comment]
>Gnat008 @Gnat008 lug 23 23:02
@ljacqu @sgdc3 Is there a reason that the tempban count is no longer reset when the player logs in? I'm pretty sure it used to

ljacqu @ljacqu lug 23 23:40
Yes, you removed it in AuthMe/AuthMeReloaded@367f785 after our discussion. We're keeping track of failure by IP, if it logs into an account successfully it shouldn't reset the temp count automatically. Maybe we could also keep track of the account the IP tried to log into or so

Gnat008 @Gnat008 00:02
Oh right. hehe. I knew that. Just that #876 seems like we're doing something wrong. Or not doing something that we should be doing.

**Comment by Gnat008** [comment]
Should this be relabled as Enhancement? I'm really not sure what to do about this. lol

**Comment by Twonox** [comment]
Reset logins failures after right login ?
Or add a configuration to reset it if we would or no.
ResetAfterRightLogin: true

**Comment by ljacqu** [comment]
Related to #764, this essentially boils down to the fact that the requirements for a successful ban manager are easy to express, but difficult to describe formally... 

This bug is caused by two things that are missing:
- Invalid login counts are never cleared
- If a player struggles to log in _x_ times into his own account and then succeeds, those failed attempts should arguably be cleared

Or, approaching it the other way around, the tempban manager should:
- ban someone that tries to log into an account _500_ times unsuccessfully
- ban someone that fires an unsuccessful login attempt for _500_ different accounts

IMHO, two things to keep in mind:
- The number of failed attempts before a captcha should be fairly low (e.g. 3 or 5), this reasonably blocks brute-force attacks by requiring interaction
- The number of failed login attempts before ban should be fairly high (say, around 20?)

It is ineffective to clear a player's fail count if he logs in successfully into an account; this means I can try 5 passwords on an admin account, log back into my own account, ad infinitum.

Before I post an idea how to implement this, does anyone else have one? Would be very interesting to hear.

**Comment by Twonox** [comment]
Or the player can change his IP...
Finaly it's not a efficient system x)
I think, the better solution is `kickOnWrongPassword: true`

**Comment by Twonox** [comment]
If we can set a wrong login count before kicking, it can be better, can't it ?

**Comment by ljacqu** [comment]
That's actually a great idea to make the number of failed attempts configurable before kicking (because immediate kick is a little extreme...). 
Then we'd have three things in our defense:
- captcha
- kicking
- tempban

**Comment by Twonox** [comment]
You can remove `kickOnWrongPassword` and apply #794 
If we can set the command to apply `/kick player` it can replace `kickOnWrongPassword` (with a reset after right login in choice)

**Comment by sgdc3** [comment]
Right ;)

**Comment by ljacqu** [comment]
Hi @Twonox and @Kixot14, build nr. 1296 or above at http://ci.xephi.fr/job/AuthMeReloaded/ contains two changes for the temporary bans. 

#### Group by IP and username
Failed login attempts are kept by IP address and now also grouped by username. This means if I fail to login as "admin" three times and as "ljacqu" four times, but then I can login as "ljacqu", the count for "ljacqu" is reset and so my IP address will only have a total of three failed login attempts (because of the "admin" ones).

#### Expiration of counts
A new setting is introduced that defines after how many minutes the count should be reset. The count of 3 for "admin" in the example above will be reset to 0 after the configured number of minutes.

May I ask you to verify if the behavior corresponds to your expectation?
