### ISSUE TITLE
No TLS email support

### ISSUE THREAD

**Issue by hraphael** [Xephi/AuthMeReloaded#910]
Can you implement for the email recover option a option to enable TLS support? Or how do I configure it?

**Comment by sgdc3** [comment]
It should be enabled by default

**Comment by hraphael** [comment]
Because I get a this message in my mail.info
`Aug 23 00:30:08 server02 postfix/smtpd[15727]: connect from unknown[XXX.XXX.XXX.XXX]`

`Aug 23 00:30:08 server02 postfix/smtpd[15727]: SSL_accept error from unknown[XXX.XXX.XXX.XXX]: 0`

`Aug 23 00:30:08 server02 postfix/smtpd[15727]: warning: TLS library problem: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:s3_pkt.c:1300:SSL alert number 46:`

`Aug 23 00:30:08 server02 postfix/smtpd[15727]: lost connection after STARTTLS from unknown[XXX.XXX.XXX.XXX]`

`Aug 23 00:30:08 server02 postfix/smtpd[15727]: disconnect from unknown[XXX.XXX.XXX.XXX]`

**Comment by ljacqu** [comment]
Could it be that you configured the wrong port? (Via [Server Fault](http://serverfault.com/questions/644085/ssl-accept-error-when-mail-client-connect-to-postfix))

Failing that, what would be interesting is if you used the same parameters in another mail client and saw if it works then. Because to me this looks like a configuration/server issue and not one on AuthMe side, but I'm happy to be proven wrong.

**Comment by hraphael** [comment]
I've tried various ports that were configured but no one worked.

**Comment by ljacqu** [comment]
Hmm, I've checked our code and we really have TLS support. All I can offer with this amount of information is to try with my own webhost to confirm that it works. 
It would be interesting to see if send emails works with the same parameters with another program. If it does, issue on our side, otherwise server issue. Do you have a server host you could contact?

**Comment by hraphael** [comment]
It is my own VPS and yes it schould work. Btw I am using port 587 with STARTTLS for auth

**Comment by ljacqu** [comment]
I can send emails fine but my host has SSL/TLS authentication. One thing about this, though, when I launch the MC server inside of my IDE (to easily run AuthMe during development) I cannot send emails and I get the same error as you. If I run the server from command line, everything works as intended. So it looks like you might be experiencing some sort of certificate issue.

The question whether you are able to send emails with another client still is unanswered. If you contact me on Gitter privately I can give you the details for an email account on my host to see if it works with that. Conversely, if you create some test email account I can also give it a try with your details on my end.

**Comment by ljacqu** [comment]
@hraphael and I talked privately. Interestingly he can send emails fine from my webservers, and even more curiously I can send emails fine using his. This leads me to believe that the issue is on hraphael's machine that is running the MC server.

Looking back at the error:

> TLS library problem: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3

If I google this I get very technical discussions I don't entirely understand but it seems that maybe this is caused by SSL 3 

https://forum.efa-project.org/viewtopic.php?t=1427
http://disablessl3.com/
http://security.stackexchange.com/questions/72985/tls-library-problem-when-connecting-to-dovecot

Some sort of config gets mentioned often, not sure where this would be or how relevant
http://www.postfix.org/postconf.5.html#smtp_tls_security_level

Simplest/safest course of action is probably to upgrade the SSL version on the mail server.
