### ISSUE TITLE
Synchronous Database Approach

### ISSUE THREAD

**Issue by Sitmobedaf** [Xephi/AuthMeReloaded#928]
Tired?! Bothered?! How much time you need to understand that you are moving in the wrong direction? You do not get to do it right - so you do not want to continue to do so. Known bugs and their more than 50. You are updating languages as if everything is already working fine. I do not want to troll, and it is not necessary to change the ban, and the truth hurt. My advice, throw this plugin, grasp the LogIt, use-synchronization unless absolutely necessary, it is necessary for example when stored in the database. We can take the base memory, and make changes to the database asynchronously, but the compound with a base (which is in memory) has been synchronized.

https://github.com/games647/LogIt

**Comment by sgdc3** [comment]
@ljacqu xD lol 
@Sitmobedaf We'll provide you a sync version of authme, so we'll see who s right. ;)

**Comment by sgdc3** [comment]
Anyway, i've unbanned you from gitter, but please keep calm and don't start insulting xD

**Comment by sgdc3** [comment]
The main issue with sync approach is the connection management, but as we use hikaricp, connections are ready to use without delays

**Comment by sgdc3** [comment]
So I really don't know if async has advantages in our case.

**Comment by sgdc3** [comment]
The issue with sync is that we can use only 1 core of the cpu and if the mysql response time is too high it would cause tps drops

**Comment by sgdc3** [comment]
I think our issue with async is that we use bukkit's scheduler instead of a custom thread pool

**Comment by sgdc3** [comment]
A thread pool would allow us to use more  cpu cores and avoid tps drops

**Comment by sgdc3** [comment]
What donyou think @ljacqu ?

**Comment by sgdc3** [comment]
We need also to keep in mind that hilaricp is already a sortnof thread pool.

**Comment by ljacqu** [comment]
I'm done dealing with Sitmobedaf. Didn't read.

**Comment by ljacqu** [comment]
I'd suggest to close this, and when a decent human being wants something like this we could visit the idea.

**Comment by Sitmobedaf** [comment]
I tried many plugins connecting to MySQL (PermissionsEx, ShoppingCartReloaded, CraftConomy, AdvancedBan, IslandWorld, BedWarsReloaded, SkyWarsReloaded, LogIt, etc...). Now work server with this plugins - mc.sparkgames.ru, delays due to the connection to the MySQL never had. Server with OS Windows Server 2012, MySQL Server - MariaDB on localhost. In asynchronous mode of plug connects to a delay in 300-1000 ms, even if the server muscles located on the local machine. AuthMe now teleport players several times, which creates excess server load as chunk load. And by the way, I have now AuthMe 3.1.1 - works fine, but just do not have many functions. But it is better than 5.1.

**Comment by ljacqu** [comment]
When does authme teleport players seceral times? I know one corcumstance when it does twice, but that's it

**Comment by Sitmobedaf** [comment]
If sessions: true (automatic authorization) - player teleport first to spawn, then to last quit location, and do it incorrect. AuthMe does not remember yaw and pitch, player after authorization have y+p=0+0
And I have a few lobby server. AuthMe requires authorization, although session: true (MySQL). In AuthMe 3.1.1 it work fine.

**Comment by ljacqu** [comment]
That describes the player being teleported twice?

> AuthMe now teleport players several times,

http://www.dictionary.com/browse/several

**Comment by bob7l** [comment]
@sgdc3 Bukkit's Async Scheduler already uses a thread pool, and HikariCP is simply a utility for keeping a group of connections open and allows for thread-safe access to said connections. So it's perfectly fine to use Bukkit's Async tasks rather then your own thread pool. 

Another thing I've noticed is your MySQL table is very bad. No indexes/keys aside from the id. This is based off my current table (Which is ~2 years old)

**Comment by ljacqu** [comment]
@bob7l Thanks for the feedback. I'm not sure I understand your first point – we don't want to use one long lived connection (hence the connection pool) and we want to talk to the database asynchronously as much as possible as not to block the main thread, right? Would you have another setup recommendation?

Regarding your second database, could we create another issue with some of your recommendations? I'll spend some time this weekend looking at what calls we make to the database; then we can get some insight as to which indexes would make sense.

**Comment by bob7l** [comment]
Uhh i believe we're mis-understanding eachother. @sgdc3 was talking about using a thread-tool instead of the bukkit-scheduler, so i simply pointed out that the bukkit-scheduler also uses a thread pool for task execution. He also claimed "hilaricp is already a sortnof thread pool." which isn't exactly valid if he means usable execution threads. 

And the problem with showing my recommendations is.. Well you don't exactly have a clean database scheme on display. It appears you utilize a group of database modifiers depending on a metadata return value. What I'd recommend is setting the "username" to a primary key assuming you're searching using this as a param. Also, don't just smack everything with VARCHAR(255) because it doesn't make sense (especially with usernames) to allocate that many characters to a lot of the columns. 

Use the InnoDB database. From my personal use, it's incredibly stable, VERY fast index searches, and so on so fourth. I've never had a dropped/failed transaction with InnoDB. 

Use a timestamp instead of a "bigint". 

Don't give "email" a default value. It's a waste of space and makes me sad. Instead, make the default null. 

Why is LoggedIn a "smallint"? It seems like you wanted the column to be a "boolean", not an integer so why the extra bytes? Use a TINYINT instead. 

 Once more, this is a VERY old database table so it might be outdated with your current scheme.

**Comment by sgdc3** [comment]
The issue with the async scheduler is that we can't control the ammount of running threads. This means that if we get 100 auth requests more than 100 threads are created

**Comment by sgdc3** [comment]
@bob7l do you understand me now? :)

**Comment by sgdc3** [comment]
basically authme is able to kill the cpu by creating tons of small threads

**Comment by sgdc3** [comment]
@bob7l we agree 100% with your ideas about the db, but atm we want to allow users to downgrade if they have issies with latest version

**Comment by sgdc3** [comment]
aftwr the 5.2 release we'll drop the old schema probably

**Comment by Sitmobedaf** [comment]
No need to connect to MuSQL server with every request to the database. Keep in memory database, save it every 3-5 seconds asynchronously.

**Comment by DNx5** [comment]
@Sitmobedaf that's what db connections pool does (HikariCP), it will keep the pool into the configured amount. except for SQLite, we only use single connection. If you have better codes, just send PR to https://github.com/AuthMe/AuthMeReloaded

**Comment by DNx5** [comment]
@bob7l we dont want to bring back the Timestamp issue (#542) and huge amount of threads bugs.

**Comment by bob7l** [comment]
@sgdc3, i haven't read AuthMe's code yet, but how exactly are you using soo much CPU for basic MySQL transactions? My HawkEye plugin inserts around 200,000 records at a 3 second interval and it hardly bogs down a thread. Maybe link me to the code? 

And the amount of threads shouldn't be an issue. I've seen pools with over 1,000 threads in web applications yet they use minimal resources. The thing that generally kills a CPU is consistent thread creation, not thread utilization. Your HikariCP library will force the threads to wait until more connections are available so you wont actually be "spamming" the MySQL so to speak (Unless you didn't set a max size?). If you're really that worried about thread usage, you could run a "AuthRequestTaskBatch" at a 1 second interval which will execute all the auth requests in a batch and call the callbacks to said requests. 

Another thing you have to think about is the fact Bukkit already has an active thread-pool, so implementing your own thread will just throw in more idling threads.

And implementing more indexing/keys would still allow for downgrading/upgrading. Indexing will simply allow for index based searches (Which are fast as fuck) instead of a regular search which in return would save a lot of resources.

**Comment by ljacqu** [comment]
Thank you @bob7l, I created another issue for your previous feedback - #931. As for the synchronous approach, as DNx5 says Sitmobedaf can submit a pull request for his improvements. If someone else cares about this let's create another issue and have a conversation about it
